#!/bin/bash

SOURCES=protobuf/boxbot.proto
GRPC_ROOT=/contrib/projects/grpc
PROTOC_ROOT=/contrib/projects/protobuf


# C++
${PROTOC_ROOT}/bin/protoc --cpp_out=build --proto_path=protobuf ${SOURCES}
${PROTOC_ROOT}/bin/protoc --grpc_out=build --proto_path=protobuf --plugin=protoc-gen-grpc=$GRPC_ROOT/bin/grpc_cpp_plugin ${SOURCES}

# PYTHON
${PROTOC_ROOT}/bin/protoc --python_out=scripts --grpc_out=scripts --plugin=protoc-gen-grpc=$GRPC_ROOT/bin/grpc_python_plugin --proto_path=protobuf ${SOURCES}

